baseurl = "https://sarayashiki.su"
title = "Sarayashiki"
theme = "ananke"
languageCode = "ru"
preserveTaxonomyNames = false
hasCJKLanguage = false


[params]
  custom_css = ["css/custom.css"]
  home_layout = "home"
  header_image = "images/main.png"
  SEOTitle = "Sarayashkik | Sarayashiki Blog"
  description = "Sarayashiki - игровой проект студентов Московского политехнического университета"
  keyword = "Sarayashiki"
  slogan = "Hack&Slash игра в сеттинге средневековой Японии"
  upstreamAttribution = false

  image_404 = "images/404.jpg"
  title_404 = "Здесь пока ничего нет..."
  omit_categories = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "О проекте"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Журнал"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "team"
    name = "Участники"
    url = "/team/"
    weight = 30

  [[menu.main]]
    identifier = "resources"
    name = "Ресурсы"
    url = "/resources/"
    weight = 40